#! /bin/sh

[global/wm]
margin-bottom = 0
margin-top = 0

;; Bars

[bar/base]
override-redirect = true
height = 22
radius = 0
offset-y = 5
background = ${color.bg0}
wm-restack = bspwm

font-0 = "Iosevka Extended:size=8;2"
font-1 = "Material Design Icons:size=12;2"
font-2 = "Weather Icons:size=12;2"
font-3 = "IPAexGothic:size=9;2"

[bar/bspwm]
inherit = bar/base
width = 10.51%
offset-x = 10.1
modules-left = bspwm
scroll-up = bspwm-wsnext
scroll-down = bspwm-wsprev
border-size = 2
border-color = ${color.green}

[bar/music]
inherit = bar/base
width = 20%
enable-ipc = true
offset-x = 12%
modules-left = previous playpause next spotify
border-size = 2
border-color = ${color.cyan}

[bar/bluetooth]
inherit = bar/base
width = 2.31%
offset-x = 51.8%
modules-left = bluetooth
border-size = 2
border-color = ${color.bg0}

[bar/keyboard]
inherit = bar/base
width = 4%
offset-x = 54.8%
modules-left = keyboard
border-size = 2
border-color = ${color.blue}

[bar/net]
inherit = bar/base
width = 9%
offset-x = 59.5%
modules-left = wifi wired
border-size = 2
border-color = ${color.violet}

[bar/volume]
inherit = bar/base
width = 5.5%
offset-x = 69.2%
modules-left = pulseaudio
border-size = 2
border-color = ${color.magenta}

[bar/bat]
inherit = bar/base
width = 5%
offset-x = 75.3%
modules-left = battery
border-size = 2
border-color = ${color.red}

[bar/weather]
inherit = bar/base
width = 5.5%
offset-x = 81.0%
modules-left = weather weather2
border-size = 2
border-color = ${color.orange}

[bar/date]
inherit = bar/base
width = 9%
offset-x = 87.1%
modules-left = date
border-size = 2
border-color = ${color.yellow}

[bar/power]
inherit = bar/base
width = 2.31%
offset-x = 96.8%
modules-left = powermenu
border-size = 2
border-color = ${color.bg0}

[settings]
screenchange-reload = true

;; Colors

[color]
alpha =   #00000000
bg0 =     #282a36
bg1 =     #14151b
fg0 =     #f8f8f2
fg1 =     #bfbfbf

red =     #ff5555
green =   #50fa7b
yellow =  #f1fa8c
blue =    #03A5C9
magenta = #ff79c6
cyan =    #8be9fd

orange =  #ffb86c
violet =  #bd93f9

;; Modules

[module/alsa]
type = internal/alsa

format-volume = <ramp-volume> <label-volume>
format-volume-background = ${color.magenta}
format-volume-foreground = ${color.bg0}
format-volume-padding = 1

label-volume = %percentage%%

format-muted-prefix = "󰖁 "
format-muted-background = ${color.magenta}
format-muted-foreground = ${color.bg0}
format-muted-padding = 1
label-muted = "Muted"

ramp-volume-0 = 󰕿
ramp-volume-1 = 󰖀
ramp-volume-2 = 󰖀
ramp-volume-3 = 󰕾
ramp-volume-4 = 󰕾

ramp-headphones-0 = 󰟎
ramp-headphones-1 = 󰋋

[module/pulseaudio]
type = internal/pulseaudio

format-volume = <ramp-volume><label-volume>
label-volume = "%percentage%%"
label-volume-background = ${color.bg0}
label-volume-foreground = ${color.magenta}
label-volume-padding = 1
use-ui-max = false
interval = 5

ramp-volume-0 = 󰕿
ramp-volume-1 = 󰖀
ramp-volume-2 = 󰕾
ramp-volume-background = ${color.magenta}
ramp-volume-foreground = ${color.bg0}
ramp-volume-padding = 1

format-muted-prefix = "󰖁 "
format-muted-background = ${color.magenta}
format-muted-foreground = ${color.bg0}
format-muted-padding = 1
label-muted = "Muted"
label-muted-background = ${color.bg0}
label-muted-foreground = ${color.magenta}
label-muted-padding = 1

[module/battery]
type = internal/battery

full-at = 99
battery = BAT1
adapter = ACAD
poll-interval = 2
time-format = %H:%M

format-charging = <animation-charging><label-charging>
format-discharging = <ramp-capacity><label-discharging>

format-full = " 100%"
format-full-prefix = 󰂄
format-full-prefix-background = ${color.red}
format-full-prefix-foreground = ${color.bg0}
format-full-prefix-padding = 1
format-full-background = ${color.bg0}
format-full-foreground = ${color.red}

label-charging = %percentage%%
label-charging-background = ${color.bg0}
label-charging-foreground = ${color.red}
label-charging-padding = 1

label-discharging = %percentage%%
label-discharging-background = ${color.bg0}
label-discharging-foreground = ${color.red}
label-discharging-padding = 1

ramp-capacity-0 = 󰁻
ramp-capacity-1 = 󰁼
ramp-capacity-2 = 󰁽
ramp-capacity-3 = 󰁾
ramp-capacity-4 = 󰂀
ramp-capacity-5 = 󰂁
ramp-capacity-6 = 󰂂
ramp-capacity-7 = 󰁹
ramp-capacity-background = ${color.red}
ramp-capacity-foreground = ${color.bg0}
ramp-capacity-padding = 1

animation-charging-0 = 󰢜
animation-charging-1 = 󰂇
animation-charging-2 = 󰢝
animation-charging-3 = 󰢞
animation-charging-background = ${color.red}
animation-charging-foreground = ${color.bg0}
animation-charging-padding = 1

animation-charging-framerate = 750

[module/cpu]
type = internal/cpu

interval = 0.5

format = <label>
format-prefix = 󰻠
format-background = ${color.cyan}
format-foreground = ${color.bg0}
format-padding = 1

label = " %percentage%%"

[module/date]
type = internal/date
interval = 1.0

time = %H:%M
date = %d %b

format = <label>
format-prefix = 󰃰
format-prefix-padding = 1
format-prefix-background = ${color.yellow}
format-prefix-foreground = ${color.bg0}
format-background = ${color.bg0}
format-foreground = ${color.yellow}
format-padding = 

label = " %time%, %date% "

click-left = firefox https://calendar.google.com/calendar/u/0/r &

[module/memory]
type = internal/memory

interval = 3

format = <label>
format-prefix = 󰍛
format-background = ${color.blue}
format-foreground = ${color.bg0}
format-padding = 1

label = " %mb_used%"

[module/previous]
type = custom/script
format-padding = 1
format-background = ${color.cyan}
format-foreground = ${color.bg0}
exec = echo "󰒮"
exec-if = "pgrep spotify"
click-left = "playerctl previous"

[module/next]
type = custom/script
format-padding = 1
format-background = ${color.cyan}
format-foreground = ${color.bg0}
exec = echo "󰒭"
exec-if = "pgrep spotify"
click-left = "playerctl next"

[module/playpause]
type = custom/script
exec = ~/.config/polybar/scripts/spotifystatus
exec-if = "pgrep spotify"
format-background = ${color.cyan}
format-foreground = ${color.bg0}
format-padding = 1
tail = true
interval = 0
click-left = "playerctl -p spotify play-pause"

[module/spotify]
type = custom/script
exec = playerctl -p spotify metadata --format '{{artist}}: {{title}}'
exec-if = "pgrep spotify"
format-background = ${color.bg0}
format-foreground = ${color.cyan}
format-padding = 1
tail = true
interval = 1

[module/mpd]
type = internal/mpd
interval = 2

format-online = <label-song>
format-online-background = ${color.bg0}
format-online-foreground = ${color.cyan}
format-online-padding = 1

label-song = "%artist% - %title%"
label-song-maxlen = 30
label-song-ellipsis = true

label-offline =

[module/mpd_i]
type = internal/mpd
interval = 2

format-online = <icon-prev> <toggle> <icon-next>
format-online-background = ${color.cyan}
format-online-foreground = ${color.bg0}
format-online-padding = 1

label-offline =

icon-play = 󰐊
icon-pause = 󰏤
icon-stop = 󰓛
icon-prev = 󰒮
icon-next = 󰒭

[module/wifi]
type = internal/network
interface = wlp0s20f3

interval = 1.0
accumulate-stats = true
unknown-as-up = true

format-connected = <ramp-signal><label-connected>
format-disconnected = <label-disconnected>
format-disconnected-background = ${color.bg0}
format-disconnected-foreground = ${color.violet}
format-disconnected-padding = 1

label-connected = %essid%
label-connected-background = ${color.bg0}
label-connected-foreground = ${color.violet}
label-connected-padding = 1

label-disconnected = 

ramp-signal-0 = 󰤫
ramp-signal-1 = 󰤟
ramp-signal-2 = 󰤢
ramp-signal-3 = 󰤥
ramp-signal-4 = 󰤨
ramp-signal-background = ${color.violet}
ramp-signal-foreground = ${color.bg0}
ramp-signal-padding = 1

[module/wired]
type = internal/network
interface = enp0s20f0u1

interval = 1.0
accumulate-stats = true
unknown-as-up = true

format-connected = <label-connected>
format-connected-prefix = "󰌗"
format-connected-prefix-background = ${color.violet}
format-connected-prefix-foreground = ${color.bg0}
format-connected-prefix-padding = 1

format-disconnected = <label-disconnected>
format-disconnected-background = ${color.violet}
format-disconnected-foreground = ${color.bg0}
format-disconnected-padding = 1

label-connected = %local_ip%
label-connected-background = ${color.bg0}
label-connected-foreground = ${color.violet}
label-connected-padding = 1

label-disconnected =

[module/weather]
type = custom/script
exec = ~/.config/polybar/scripts/openweathermap-fullfeatured.sh
interval = 600
format = <label>
format-background = ${color.orange}
format-foreground = ${color.bg0}
label-padding = 1
click-left = firefox https://openweathermap.org/city/3439389 &

[module/weather2]
type = custom/script
exec = ~/.config/polybar/scripts/openweathermap2.sh
interval = 600
format = <label>
format-background = ${color.bg0}
format-foreground = ${color.orange}
label-padding = 1

[module/title]
type = internal/xwindow
format = <label>
format-prefix = "󰖯 "
format-background = ${color.cyan}
format-foreground = ${color.bg0}
label = %title%
label-maxlen = 20
format-padding = 1

[module/keyboard]
type = internal/xkeyboard
blacklist-0 = num lock
blacklist-1 = scroll lock
blacklist-2 = caps lock

format = <label-layout><label-indicator>
format-prefix = "󰥻"
format-prefix-background = ${color.blue}
format-prefix-foreground = ${color.bg0}
format-prefix-padding = 1

label-layout = %layout%
label-layout-background = ${color.bg0}
label-layout-foreground = ${color.blue}
label-layout-padding = 1

label-indicator-on = %name%
label-indicator-on-foreground = ${color.bg0}

[module/powermenu]
type = custom/text
content = 󰐥
content-foreground = ${color.red}
content-background = ${color.bg0}
click-left = ~/.config/rofi/scripts/powermenu.sh
content-padding = 1

[module/bspwm]
type = internal/bspwm

ws-icon-0 = I;󰖟
ws-icon-1 = II;󰞷
ws-icon-2 = III;󰪶
ws-icon-3 = IV;󰧮
ws-icon-4 = V;󰩭
ws-icon-5 = VI;󰱦
ws-icon-6 = VII;󰻞
ws-icon-7 = VIII;󰢹
ws-icon-8 = IX;󰷝
ws-icon-9 = X;󰓇

format = <label-state> <label-mode>
label-mode = %mode%
label-mode-padding = 1
label-mode-background = ${color.bg0}

label-focused = %icon%
label-focused-foreground = ${color.bg0}
label-focused-background = ${color.green}
label-focused-padding = 1

label-occupied = %icon%
label-occupied-foreground = ${color.green}
label-occupied-background = ${color.bg0}
label-occupied-padding = 1

label-urgent = %icon%
label-urgent-foreground = ${color.violet}
label-urgent-background = ${color.red}
label-urgent-padding = 1

label-empty = 
label-empty-foreground = ${color.green}
label-empty-background = ${color.bg0}
label-empty-padding = 1

[module/bluetooth]
type = custom/script
exec = /home/mura/.config/polybar/scripts/bluetooth.sh
interval = 2
tail = true
click-left = exec blueberry
click-right = exec /home/mura/.config/polybar/scripts/toggle_bluetooth.sh
format-prefix = "󰂯"
format-padding = 1
format-background = ${color.bg0}
format-foreground = ${color.blue}
