#! /bin/sh

[global/wm]
margin-bottom = 0
margin-top = 0

;; Bar

[bar/base]
override-redirect = true
width = 98.4%
height = 26
radius = 0
offset-x = 10
offset-y = 2
background = ${color.bg0}
wm-restack = bspwm
#border-size = 2
#border-color = ${color.bg1}

font-0 = "Iosevka Extended:size=8;2"
font-1 = "Material Design Icons:size=12;2"
font-2 = "Weather Icons:size=10;2"
font-3 = "IPAexGothic:size=9;2"

modules-left = bspwm previous playpause next spotify
modules-center = date weather weather2
modules-right = cpu memory wifi wired battery pulseaudio keyboard bluetooth powermenu

[settings]
screenchange-reload = true

;; Colors

[color]
alpha =   #00000000
bg0 =     #1a1a1a
bg1 =     #303030
fg0 =     #f6f6ef
fg1 =     #c4c5b5

red =     #f4005f
green =   #98e924
yellow =  #e6db74
blue =    #58d1eb
magenta = #fd5ff0
cyan =    #a1efe4

orange =  #fa8419
violet =  #9d65ff

;; Modules

[module/pulseaudio]
type = internal/pulseaudio

format-volume = <ramp-volume><label-volume>
label-volume = "%percentage%%"
label-volume-background = ${color.bg0}
label-volume-foreground = ${color.orange}
label-volume-padding = 1
use-ui-max = false
interval = 5

ramp-volume-0 = 󰕿
ramp-volume-1 = 󰖀
ramp-volume-2 = 󰕾
ramp-volume-background = ${color.bg0}
ramp-volume-foreground = ${color.orange}
ramp-volume-padding = 1

format-muted-prefix = "󰖁"
format-muted-background = ${color.bg0}
format-muted-foreground = ${color.orange}
format-muted-padding = 1
label-muted = "Muted"
label-muted-background = ${color.bg0}
label-muted-foreground = ${color.orange}
label-muted-padding = 1

[module/battery]
type = internal/battery

full-at = 99
battery = BAT1
adapter = ACAD
poll-interval = 2
time-format = %H:%M

format-charging = <animation-charging><label-charging>
format-discharging = <ramp-capacity><label-discharging>

format-full = "100%"
format-full-prefix = 󰂄
format-full-prefix-background = ${color.bg0}
format-full-prefix-foreground = ${color.magenta}
format-full-prefix-padding = 1
format-full-background = ${color.bg0}
format-full-foreground = ${color.magenta}

label-charging = %percentage%%
label-charging-background = ${color.bg0}
label-charging-foreground = ${color.magenta}
label-charging-padding = 1

label-discharging = %percentage%%
label-discharging-background = ${color.bg0}
label-discharging-foreground = ${color.magenta}
label-discharging-padding = 1

ramp-capacity-0 = 󰁻
ramp-capacity-1 = 󰁼
ramp-capacity-2 = 󰁽
ramp-capacity-3 = 󰁾
ramp-capacity-4 = 󰂀
ramp-capacity-5 = 󰂁
ramp-capacity-6 = 󰂂
ramp-capacity-7 = 󰁹
ramp-capacity-background = ${color.bg0}
ramp-capacity-foreground = ${color.magenta}
ramp-capacity-padding = 1

animation-charging-0 = 󰢜
animation-charging-1 = 󰂇
animation-charging-2 = 󰢝
animation-charging-3 = 󰢞
animation-charging-background = ${color.bg0}
animation-charging-foreground = ${color.magenta}
animation-charging-padding = 1

animation-charging-framerate = 750

[module/cpu]
type = internal/cpu

interval = 0.5

format = <label>
format-prefix = 󰻠
format-background = ${color.bg0}
format-foreground = ${color.cyan}
format-padding = 1

label = " %percentage%%"

[module/date]
type = internal/date
interval = 1.0

time = %H:%M
date = %d %b

format = <label>
format-prefix = 󰃰
format-prefix-padding = 1
format-prefix-background = ${color.bg0}
format-prefix-foreground = ${color.fg1}
format-background = ${color.bg0}
format-foreground = ${color.fg1}
format-padding = 1

label = "%date% %time%"

[module/memory]
type = internal/memory

interval = 3

format = <label>
format-prefix = 󰍛
format-background = ${color.bg0}
format-foreground = ${color.blue}
format-padding = 1

label = " %mb_used%"

[module/previous]
type = custom/script
format-padding = 1
format-background = ${color.bg0}
format-foreground = ${color.fg1}
exec = echo "󰒮"
exec-if = "pgrep spotify"
click-left = "playerctl previous"

[module/next]
type = custom/script
format-padding = 1
format-background = ${color.bg0}
format-foreground = ${color.fg1}
exec = echo "󰒭"
exec-if = "pgrep spotify"
click-left = "playerctl next"

[module/playpause]
type = custom/script
exec = ~/.config/polybar/scripts/spotifystatus
exec-if = "pgrep spotify"
format-background = ${color.bg0}
format-foreground = ${color.fg1}
format-padding = 0
tail = true
interval = 0
click-left = "playerctl -p spotify play-pause"

[module/spotify]
type = custom/script
exec = playerctl -p spotify metadata --format '{{artist}}: {{title}}'
exec-if = "pgrep spotify"
format-background = ${color.bg0}
format-foreground = ${color.fg1}
format-padding = 1
tail = true
interval = 1

[module/wifi]
type = internal/network
interface = wlp0s20f3

interval = 1.0
accumulate-stats = true
unknown-as-up = true

format-connected = <ramp-signal><label-connected>
format-disconnected = <label-disconnected>
format-disconnected-background = ${color.bg0}
format-disconnected-foreground = ${color.violet}
format-disconnected-padding = 1

label-connected = %essid%
label-connected-background = ${color.bg0}
label-connected-foreground = ${color.violet}
label-connected-padding = 1

label-disconnected = 

ramp-signal-0 = 󰤫
ramp-signal-1 = 󰤟
ramp-signal-2 = 󰤢
ramp-signal-3 = 󰤥
ramp-signal-4 = 󰤨
ramp-signal-background = ${color.bg0}
ramp-signal-foreground = ${color.violet}
ramp-signal-padding = 1

[module/wired]
type = internal/network
interface = enp0s20f0u1

interval = 1.0
accumulate-stats = true
unknown-as-up = true

format-connected = <label-connected>
format-connected-prefix = "󰌗"
format-connected-prefix-background = ${color.bg0}
format-connected-prefix-foreground = ${color.violet}
format-connected-prefix-padding = 1

format-disconnected = <label-disconnected>
format-disconnected-background = ${color.bg0}
format-disconnected-foreground = ${color.violet}
format-disconnected-padding = 1

label-connected = %local_ip%
label-connected-background = ${color.bg0}
label-connected-foreground = ${color.violet}
label-connected-padding = 1

label-disconnected =

[module/weather]
type = custom/script
exec = ~/.config/polybar/scripts/openweathermap-fullfeatured.sh
interval = 600
format = <label>
format-background = ${color.bg0}
format-foreground = ${color.fg1}
format-padding = 1
label-padding-left = 1
click-left = firefox https://openweathermap.org/city/3439389 &

[module/weather2]
type = custom/script
exec = ~/.config/polybar/scripts/openweathermap2.sh
interval = 600
format = <label>
format-background = ${color.bg0}
format-foreground = ${color.fg1}
label-padding = 0

[module/title]
type = internal/xwindow
format = <label>
format-prefix = "󰖯 "
format-background = ${color.cyan}
format-foreground = ${color.bg0}
label = %title%
label-maxlen = 20
format-padding = 1

[module/keyboard]
type = internal/xkeyboard
blacklist-0 = num lock
blacklist-1 = scroll lock
blacklist-2 = caps lock

format = <label-layout><label-indicator>
format-prefix = "󰥻"
format-prefix-background = ${color.bg0}
format-prefix-foreground = ${color.yellow}
format-prefix-padding = 1

label-layout = %layout%
label-layout-background = ${color.bg0}
label-layout-foreground = ${color.yellow}
label-layout-padding = 1

label-indicator-on = %name%
label-indicator-on-foreground = ${color.bg0}

[module/powermenu]
type = custom/text
content = 󰐥
content-foreground = ${color.red}
content-background = ${color.bg0}
click-left = ~/.config/rofi/scripts/powermenu.sh
content-padding = 1

[module/bspwm]
type = internal/bspwm

ws-icon-0 = I;󰖟
ws-icon-1 = II;󰞷
ws-icon-2 = III;󰪶
ws-icon-3 = IV;󰧮
ws-icon-4 = V;󰩭
ws-icon-5 = VI;󰱦
ws-icon-6 = VII;󰻞
ws-icon-7 = VIII;󰢹
ws-icon-8 = IX;󰷝
ws-icon-9 = X;󰓇

format = <label-state> <label-mode>
label-mode = %mode%
label-mode-padding = 1
label-mode-background = ${color.bg0}

label-focused = %icon%
label-focused-foreground = ${color.green}
label-focused-background = ${color.bg0}
label-focused-padding = 1

label-occupied = %icon%
label-occupied-foreground = ${color.bg1}
label-occupied-background = ${color.bg0}
label-occupied-padding = 1

label-urgent = %icon%
label-urgent-foreground = ${color.red}
label-urgent-background = ${color.bg0}
label-urgent-padding = 1

label-empty = 
label-empty-foreground = ${color.bg1}
label-empty-background = ${color.bg0}
label-empty-padding = 1

[module/bluetooth]
type = custom/script
exec = /home/mura/.config/polybar/scripts/bluetooth.sh
interval = 2
tail = true
click-left = exec blueberry
click-right = exec /home/mura/.config/polybar/scripts/toggle_bluetooth.sh
format-padding = 1
format-background = ${color.bg0}
format-foreground = ${color.red}
